services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
       - ./postgres:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    restart: always

# Use postgres/example user/password credentials
# version: '3.9'

# services:
#   postgres:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_USER: luisdev
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: exampledb
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres:/var/lib/postgresql/data